name: dependencies
description: A new Flutter package.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  fluttertoast: ^7.1.6
  flutter_svg: ^0.19.3
  shimmer: ^1.1.2

  # Core
  flutter_bloc: ^6.1.1
  shared_preferences: ^0.5.12+4
  equatable: ^1.2.5
  get_it: ^5.0.3
  dio: ^3.0.10
  #built_value_generator: ^6.7.1
  http: ^0.12.0
  package_info: ^0.4.3+4
  persistent_bottom_nav_bar: ^3.1.0
  # Animations
  simple_animations: ^1.3.3
  # custom bottom sheet
  stacked_services: ^0.7.3
  # dotted border
  dotted_border: ^1.0.7
  # ColorPicker
  flutter_colorpicker: ^0.4.0

  #json_annotation: ^3.0.0
  json_serializable: ^3.5.1
  build_runner: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: